### ISSUE TITLE
[question] How can I add a proxy IP as a parameter to the algolia API request?

### ISSUE THREAD

**Issue by juanfrilla** [algolia/renderscript#861]
How can I add a proxy IP as a parameter to the algolia API request to make the call through that proxy?

**Comment by dylantientcheu** [comment]
If i understand correctly, you are trying to Crawl a website through a proxy ?

We do not proxy Algolia Crawler requests as the end website is waiting for our Crawler we always send the requests with the same IP [docs](https://www.algolia.com/doc/tools/crawler/troubleshooting/fetching-issues/#solution-7).

If this question is about Algolia Search, you can have more information see the docs here: https://www.algolia.com/doc/libraries/javascript/v5/customize/
